// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// DSN provides a mock function for the type MockProvider
func (_mock *MockProvider) DSN() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DSN")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_DSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DSN'
type MockProvider_DSN_Call struct {
	*mock.Call
}

// DSN is a helper method to define mock.On call
func (_e *MockProvider_Expecter) DSN() *MockProvider_DSN_Call {
	return &MockProvider_DSN_Call{Call: _e.mock.On("DSN")}
}

func (_c *MockProvider_DSN_Call) Run(run func()) *MockProvider_DSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_DSN_Call) Return(s string) *MockProvider_DSN_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_DSN_Call) RunAndReturn(run func() string) *MockProvider_DSN_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConnIdleTime provides a mock function for the type MockProvider
func (_mock *MockProvider) MaxConnIdleTime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConnIdleTime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockProvider_MaxConnIdleTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConnIdleTime'
type MockProvider_MaxConnIdleTime_Call struct {
	*mock.Call
}

// MaxConnIdleTime is a helper method to define mock.On call
func (_e *MockProvider_Expecter) MaxConnIdleTime() *MockProvider_MaxConnIdleTime_Call {
	return &MockProvider_MaxConnIdleTime_Call{Call: _e.mock.On("MaxConnIdleTime")}
}

func (_c *MockProvider_MaxConnIdleTime_Call) Run(run func()) *MockProvider_MaxConnIdleTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_MaxConnIdleTime_Call) Return(duration time.Duration) *MockProvider_MaxConnIdleTime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockProvider_MaxConnIdleTime_Call) RunAndReturn(run func() time.Duration) *MockProvider_MaxConnIdleTime_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConnLifetime provides a mock function for the type MockProvider
func (_mock *MockProvider) MaxConnLifetime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConnLifetime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockProvider_MaxConnLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConnLifetime'
type MockProvider_MaxConnLifetime_Call struct {
	*mock.Call
}

// MaxConnLifetime is a helper method to define mock.On call
func (_e *MockProvider_Expecter) MaxConnLifetime() *MockProvider_MaxConnLifetime_Call {
	return &MockProvider_MaxConnLifetime_Call{Call: _e.mock.On("MaxConnLifetime")}
}

func (_c *MockProvider_MaxConnLifetime_Call) Run(run func()) *MockProvider_MaxConnLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_MaxConnLifetime_Call) Return(duration time.Duration) *MockProvider_MaxConnLifetime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockProvider_MaxConnLifetime_Call) RunAndReturn(run func() time.Duration) *MockProvider_MaxConnLifetime_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConns provides a mock function for the type MockProvider
func (_mock *MockProvider) MaxConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockProvider_MaxConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConns'
type MockProvider_MaxConns_Call struct {
	*mock.Call
}

// MaxConns is a helper method to define mock.On call
func (_e *MockProvider_Expecter) MaxConns() *MockProvider_MaxConns_Call {
	return &MockProvider_MaxConns_Call{Call: _e.mock.On("MaxConns")}
}

func (_c *MockProvider_MaxConns_Call) Run(run func()) *MockProvider_MaxConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_MaxConns_Call) Return(n int32) *MockProvider_MaxConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProvider_MaxConns_Call) RunAndReturn(run func() int32) *MockProvider_MaxConns_Call {
	_c.Call.Return(run)
	return _c
}

// MinConns provides a mock function for the type MockProvider
func (_mock *MockProvider) MinConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MinConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockProvider_MinConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinConns'
type MockProvider_MinConns_Call struct {
	*mock.Call
}

// MinConns is a helper method to define mock.On call
func (_e *MockProvider_Expecter) MinConns() *MockProvider_MinConns_Call {
	return &MockProvider_MinConns_Call{Call: _e.mock.On("MinConns")}
}

func (_c *MockProvider_MinConns_Call) Run(run func()) *MockProvider_MinConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_MinConns_Call) Return(n int32) *MockProvider_MinConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProvider_MinConns_Call) RunAndReturn(run func() int32) *MockProvider_MinConns_Call {
	_c.Call.Return(run)
	return _c
}
