CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    login VARCHAR(100) NOT NULL,
    password_hash CHAR(60) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_login UNIQUE (login)
    );

COMMENT ON COLUMN customer.id IS 'уникальный идентификатор покупателя, автоинкремент';
COMMENT ON COLUMN customer.login IS 'уникальный логин покупателя';
COMMENT ON COLUMN customer.password_hash IS 'хеш от пароля покупателя';
COMMENT ON COLUMN customer.created_at IS 'когда создана запись';
