CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    "number" VARCHAR(20) NOT NULL,
    customer_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    accrual NUMERIC(10, 2) NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_number UNIQUE (number)
    );

CREATE INDEX IF NOT EXISTS idx_orders_customer_uploaded ON orders (customer_id, uploaded_at DESC);

COMMENT ON TABLE  orders               IS 'заказы покупателей системы лояльности';
COMMENT ON COLUMN orders.id            IS 'уникальный идентификатор заказа';
COMMENT ON COLUMN orders.number        IS 'уникальный номер заказа';
COMMENT ON COLUMN orders.customer_id   IS 'id покупателя, которому принадлежит заказ';
COMMENT ON COLUMN orders.status        IS 'статус обработки расчёта';
COMMENT ON COLUMN orders.accrual       IS 'начисленные баллы';
COMMENT ON COLUMN orders.uploaded_at   IS 'когда заказ был загружен';