CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL CHECK (id >= 0),
    login VARCHAR(20) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_login UNIQUE (login)
);

COMMENT ON TABLE  customers IS 'покупатели системы лояльности';
COMMENT ON COLUMN customers.id IS 'уникальный идентификатор покупателя, автоинкремент';
COMMENT ON COLUMN customers.login IS 'уникальный логин покупателя';
COMMENT ON COLUMN customers.password_hash IS 'хеш от пароля покупателя';
COMMENT ON COLUMN customers.created_at IS 'когда создана запись';
