CREATE TABLE IF NOT EXISTS withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    order_id BIGINT NOT NULL CHECK (id >= 0),
    "sum" NUMERIC(10, 2) NOT NULL CHECK (id >= 0),
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    );

CREATE INDEX IF NOT EXISTS idx_withdrawals_order_processed ON withdrawals (order_id, processed_at DESC);

COMMENT ON TABLE  withdrawals               IS 'информация о выводе средств';
COMMENT ON COLUMN withdrawals.id            IS 'уникальный идентификатор списания';
COMMENT ON COLUMN withdrawals.order_id      IS 'id заказа';
COMMENT ON COLUMN withdrawals.sum           IS 'сумма списания';
COMMENT ON COLUMN withdrawals.processed_at  IS 'когда было списание';