CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    login VARCHAR(20) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_login UNIQUE (login)
    );

COMMENT ON COLUMN customers.id IS 'уникальный идентификатор покупателя, автоинкремент';
COMMENT ON COLUMN customers.login IS 'уникальный логин покупателя';
COMMENT ON COLUMN customers.password_hash IS 'хеш от пароля покупателя';
COMMENT ON COLUMN customers.created_at IS 'когда создана запись';
