// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/dto"
	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoyaltyStorage creates a new instance of MockLoyaltyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyStorage {
	mock := &MockLoyaltyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyStorage is an autogenerated mock type for the LoyaltyStorage type
type MockLoyaltyStorage struct {
	mock.Mock
}

type MockLoyaltyStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyStorage) EXPECT() *MockLoyaltyStorage_Expecter {
	return &MockLoyaltyStorage_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) Balance(ctx context.Context, userDTO *dto.User) (*model.Balance, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 *model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) (*model.Balance, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) *model.Balance); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type MockLoyaltyStorage_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyStorage_Expecter) Balance(ctx any, userDTO any) *MockLoyaltyStorage_Balance_Call {
	return &MockLoyaltyStorage_Balance_Call{Call: _e.mock.On("Balance", ctx, userDTO)}
}

func (_c *MockLoyaltyStorage_Balance_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyStorage_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_Balance_Call) Return(balance *model.Balance, err error) *MockLoyaltyStorage_Balance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockLoyaltyStorage_Balance_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) (*model.Balance, error)) *MockLoyaltyStorage_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdraw provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceWithdraw(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64) error {
	ret := _mock.Called(ctx, userDTO, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User, string, float64) error); ok {
		r0 = returnFunc(ctx, userDTO, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyStorage_BalanceWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdraw'
type MockLoyaltyStorage_BalanceWithdraw_Call struct {
	*mock.Call
}

// BalanceWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
//   - orderNumber string
//   - sum float64
func (_e *MockLoyaltyStorage_Expecter) BalanceWithdraw(ctx any, userDTO any, orderNumber any, sum any) *MockLoyaltyStorage_BalanceWithdraw_Call {
	return &MockLoyaltyStorage_BalanceWithdraw_Call{Call: _e.mock.On("BalanceWithdraw", ctx, userDTO, orderNumber, sum)}
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) Run(run func(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64)) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) Return(err error) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64) error) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdrawals provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceWithdrawals(ctx context.Context, userDTO *dto.User) ([]model.Withdrawal, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) ([]model.Withdrawal, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) []model.Withdrawal); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_BalanceWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdrawals'
type MockLoyaltyStorage_BalanceWithdrawals_Call struct {
	*mock.Call
}

// BalanceWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyStorage_Expecter) BalanceWithdrawals(ctx any, userDTO any) *MockLoyaltyStorage_BalanceWithdrawals_Call {
	return &MockLoyaltyStorage_BalanceWithdrawals_Call{Call: _e.mock.On("BalanceWithdrawals", ctx, userDTO)}
}

func (_c *MockLoyaltyStorage_BalanceWithdrawals_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyStorage_BalanceWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdrawals_Call) Return(withdrawals []model.Withdrawal, err error) *MockLoyaltyStorage_BalanceWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) ([]model.Withdrawal, error)) *MockLoyaltyStorage_BalanceWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// OrderUpload provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) OrderUpload(ctx context.Context, userDTO *dto.User, number string) error {
	ret := _mock.Called(ctx, userDTO, number)

	if len(ret) == 0 {
		panic("no return value specified for OrderUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User, string) error); ok {
		r0 = returnFunc(ctx, userDTO, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyStorage_OrderUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderUpload'
type MockLoyaltyStorage_OrderUpload_Call struct {
	*mock.Call
}

// OrderUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
//   - number string
func (_e *MockLoyaltyStorage_Expecter) OrderUpload(ctx any, userDTO any, number any) *MockLoyaltyStorage_OrderUpload_Call {
	return &MockLoyaltyStorage_OrderUpload_Call{Call: _e.mock.On("OrderUpload", ctx, userDTO, number)}
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) Run(run func(ctx context.Context, userDTO *dto.User, number string)) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) Return(err error) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User, number string) error) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Orders provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) Orders(ctx context.Context, userDTO *dto.User) ([]model.Order, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) ([]model.Order, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) []model.Order); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type MockLoyaltyStorage_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyStorage_Expecter) Orders(ctx any, userDTO any) *MockLoyaltyStorage_Orders_Call {
	return &MockLoyaltyStorage_Orders_Call{Call: _e.mock.On("Orders", ctx, userDTO)}
}

func (_c *MockLoyaltyStorage_Orders_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyStorage_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_Orders_Call) Return(orders []model.Order, err error) *MockLoyaltyStorage_Orders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyStorage_Orders_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) ([]model.Order, error)) *MockLoyaltyStorage_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// UserByLogin provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) UserByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for UserByLogin")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_UserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByLogin'
type MockLoyaltyStorage_UserByLogin_Call struct {
	*mock.Call
}

// UserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockLoyaltyStorage_Expecter) UserByLogin(ctx any, login any) *MockLoyaltyStorage_UserByLogin_Call {
	return &MockLoyaltyStorage_UserByLogin_Call{Call: _e.mock.On("UserByLogin", ctx, login)}
}

func (_c *MockLoyaltyStorage_UserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockLoyaltyStorage_UserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_UserByLogin_Call) Return(user *model.User, err error) *MockLoyaltyStorage_UserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockLoyaltyStorage_UserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (*model.User, error)) *MockLoyaltyStorage_UserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UserCreate provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) UserCreate(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_UserCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCreate'
type MockLoyaltyStorage_UserCreate_Call struct {
	*mock.Call
}

// UserCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockLoyaltyStorage_Expecter) UserCreate(ctx any, user any) *MockLoyaltyStorage_UserCreate_Call {
	return &MockLoyaltyStorage_UserCreate_Call{Call: _e.mock.On("UserCreate", ctx, user)}
}

func (_c *MockLoyaltyStorage_UserCreate_Call) Run(run func(ctx context.Context, user *model.User)) *MockLoyaltyStorage_UserCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_UserCreate_Call) Return(user1 *model.User, err error) *MockLoyaltyStorage_UserCreate_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockLoyaltyStorage_UserCreate_Call) RunAndReturn(run func(ctx context.Context, user *model.User) (*model.User, error)) *MockLoyaltyStorage_UserCreate_Call {
	_c.Call.Return(run)
	return _c
}
