// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// AccrualSystemAddress provides a mock function for the type MockProvider
func (_mock *MockProvider) AccrualSystemAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccrualSystemAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_AccrualSystemAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccrualSystemAddress'
type MockProvider_AccrualSystemAddress_Call struct {
	*mock.Call
}

// AccrualSystemAddress is a helper method to define mock.On call
func (_e *MockProvider_Expecter) AccrualSystemAddress() *MockProvider_AccrualSystemAddress_Call {
	return &MockProvider_AccrualSystemAddress_Call{Call: _e.mock.On("AccrualSystemAddress")}
}

func (_c *MockProvider_AccrualSystemAddress_Call) Run(run func()) *MockProvider_AccrualSystemAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_AccrualSystemAddress_Call) Return(s string) *MockProvider_AccrualSystemAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_AccrualSystemAddress_Call) RunAndReturn(run func() string) *MockProvider_AccrualSystemAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Address provides a mock function for the type MockProvider
func (_mock *MockProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Address() *MockProvider_Address_Call {
	return &MockProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockProvider_Address_Call) Run(run func()) *MockProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Address_Call) Return(s string) *MockProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Address_Call) RunAndReturn(run func() string) *MockProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// JWTSecret provides a mock function for the type MockProvider
func (_mock *MockProvider) JWTSecret() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWTSecret")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_JWTSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWTSecret'
type MockProvider_JWTSecret_Call struct {
	*mock.Call
}

// JWTSecret is a helper method to define mock.On call
func (_e *MockProvider_Expecter) JWTSecret() *MockProvider_JWTSecret_Call {
	return &MockProvider_JWTSecret_Call{Call: _e.mock.On("JWTSecret")}
}

func (_c *MockProvider_JWTSecret_Call) Run(run func()) *MockProvider_JWTSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_JWTSecret_Call) Return(s string) *MockProvider_JWTSecret_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_JWTSecret_Call) RunAndReturn(run func() string) *MockProvider_JWTSecret_Call {
	_c.Call.Return(run)
	return _c
}
