// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/dto"
	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/status/inner"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoyaltyManageable creates a new instance of MockLoyaltyManageable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyManageable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyManageable {
	mock := &MockLoyaltyManageable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyManageable is an autogenerated mock type for the LoyaltyManageable type
type MockLoyaltyManageable struct {
	mock.Mock
}

type MockLoyaltyManageable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyManageable) EXPECT() *MockLoyaltyManageable_Expecter {
	return &MockLoyaltyManageable_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) Balance(ctx context.Context, customerDTO *dto.Customer) (dto.Balance, error) {
	ret := _mock.Called(ctx, customerDTO)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 dto.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) (dto.Balance, error)); ok {
		return returnFunc(ctx, customerDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) dto.Balance); ok {
		r0 = returnFunc(ctx, customerDTO)
	} else {
		r0 = ret.Get(0).(dto.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.Customer) error); ok {
		r1 = returnFunc(ctx, customerDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type MockLoyaltyManageable_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - customerDTO *dto.Customer
func (_e *MockLoyaltyManageable_Expecter) Balance(ctx any, customerDTO any) *MockLoyaltyManageable_Balance_Call {
	return &MockLoyaltyManageable_Balance_Call{Call: _e.mock.On("Balance", ctx, customerDTO)}
}

func (_c *MockLoyaltyManageable_Balance_Call) Run(run func(ctx context.Context, customerDTO *dto.Customer)) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Customer
		if args[1] != nil {
			arg1 = args[1].(*dto.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_Balance_Call) Return(balance dto.Balance, err error) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockLoyaltyManageable_Balance_Call) RunAndReturn(run func(ctx context.Context, customerDTO *dto.Customer) (dto.Balance, error)) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceAccrual provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) BalanceAccrual(ctx context.Context, accrual dto.Accrual) error {
	ret := _mock.Called(ctx, accrual)

	if len(ret) == 0 {
		panic("no return value specified for BalanceAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Accrual) error); ok {
		r0 = returnFunc(ctx, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyManageable_BalanceAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceAccrual'
type MockLoyaltyManageable_BalanceAccrual_Call struct {
	*mock.Call
}

// BalanceAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - accrual dto.Accrual
func (_e *MockLoyaltyManageable_Expecter) BalanceAccrual(ctx any, accrual any) *MockLoyaltyManageable_BalanceAccrual_Call {
	return &MockLoyaltyManageable_BalanceAccrual_Call{Call: _e.mock.On("BalanceAccrual", ctx, accrual)}
}

func (_c *MockLoyaltyManageable_BalanceAccrual_Call) Run(run func(ctx context.Context, accrual dto.Accrual)) *MockLoyaltyManageable_BalanceAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.Accrual
		if args[1] != nil {
			arg1 = args[1].(dto.Accrual)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_BalanceAccrual_Call) Return(err error) *MockLoyaltyManageable_BalanceAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyManageable_BalanceAccrual_Call) RunAndReturn(run func(ctx context.Context, accrual dto.Accrual) error) *MockLoyaltyManageable_BalanceAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdraw provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) BalanceWithdraw(ctx context.Context, customerDTO *dto.Customer, withdraw dto.BalanceWithdraw) error {
	ret := _mock.Called(ctx, customerDTO, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer, dto.BalanceWithdraw) error); ok {
		r0 = returnFunc(ctx, customerDTO, withdraw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyManageable_BalanceWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdraw'
type MockLoyaltyManageable_BalanceWithdraw_Call struct {
	*mock.Call
}

// BalanceWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - customerDTO *dto.Customer
//   - withdraw dto.BalanceWithdraw
func (_e *MockLoyaltyManageable_Expecter) BalanceWithdraw(ctx any, customerDTO any, withdraw any) *MockLoyaltyManageable_BalanceWithdraw_Call {
	return &MockLoyaltyManageable_BalanceWithdraw_Call{Call: _e.mock.On("BalanceWithdraw", ctx, customerDTO, withdraw)}
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) Run(run func(ctx context.Context, customerDTO *dto.Customer, withdraw dto.BalanceWithdraw)) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Customer
		if args[1] != nil {
			arg1 = args[1].(*dto.Customer)
		}
		var arg2 dto.BalanceWithdraw
		if args[2] != nil {
			arg2 = args[2].(dto.BalanceWithdraw)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) Return(err error) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) RunAndReturn(run func(ctx context.Context, customerDTO *dto.Customer, withdraw dto.BalanceWithdraw) error) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdrawals provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) BalanceWithdrawals(ctx context.Context, customerDTO *dto.Customer) ([]dto.Withdrawal, error) {
	ret := _mock.Called(ctx, customerDTO)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdrawals")
	}

	var r0 []dto.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) ([]dto.Withdrawal, error)); ok {
		return returnFunc(ctx, customerDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) []dto.Withdrawal); ok {
		r0 = returnFunc(ctx, customerDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.Customer) error); ok {
		r1 = returnFunc(ctx, customerDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_BalanceWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdrawals'
type MockLoyaltyManageable_BalanceWithdrawals_Call struct {
	*mock.Call
}

// BalanceWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - customerDTO *dto.Customer
func (_e *MockLoyaltyManageable_Expecter) BalanceWithdrawals(ctx any, customerDTO any) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	return &MockLoyaltyManageable_BalanceWithdrawals_Call{Call: _e.mock.On("BalanceWithdrawals", ctx, customerDTO)}
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) Run(run func(ctx context.Context, customerDTO *dto.Customer)) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Customer
		if args[1] != nil {
			arg1 = args[1].(*dto.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) Return(withdrawals []dto.Withdrawal, err error) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) RunAndReturn(run func(ctx context.Context, customerDTO *dto.Customer) ([]dto.Withdrawal, error)) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// OrderUpload provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) OrderUpload(ctx context.Context, customerDTO *dto.Customer, number string) error {
	ret := _mock.Called(ctx, customerDTO, number)

	if len(ret) == 0 {
		panic("no return value specified for OrderUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer, string) error); ok {
		r0 = returnFunc(ctx, customerDTO, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyManageable_OrderUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderUpload'
type MockLoyaltyManageable_OrderUpload_Call struct {
	*mock.Call
}

// OrderUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - customerDTO *dto.Customer
//   - number string
func (_e *MockLoyaltyManageable_Expecter) OrderUpload(ctx any, customerDTO any, number any) *MockLoyaltyManageable_OrderUpload_Call {
	return &MockLoyaltyManageable_OrderUpload_Call{Call: _e.mock.On("OrderUpload", ctx, customerDTO, number)}
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) Run(run func(ctx context.Context, customerDTO *dto.Customer, number string)) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Customer
		if args[1] != nil {
			arg1 = args[1].(*dto.Customer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) Return(err error) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) RunAndReturn(run func(ctx context.Context, customerDTO *dto.Customer, number string) error) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Orders provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) Orders(ctx context.Context, customerDTO *dto.Customer) ([]dto.Order, error) {
	ret := _mock.Called(ctx, customerDTO)

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 []dto.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) ([]dto.Order, error)); ok {
		return returnFunc(ctx, customerDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Customer) []dto.Order); ok {
		r0 = returnFunc(ctx, customerDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.Customer) error); ok {
		r1 = returnFunc(ctx, customerDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type MockLoyaltyManageable_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
//   - ctx context.Context
//   - customerDTO *dto.Customer
func (_e *MockLoyaltyManageable_Expecter) Orders(ctx any, customerDTO any) *MockLoyaltyManageable_Orders_Call {
	return &MockLoyaltyManageable_Orders_Call{Call: _e.mock.On("Orders", ctx, customerDTO)}
}

func (_c *MockLoyaltyManageable_Orders_Call) Run(run func(ctx context.Context, customerDTO *dto.Customer)) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Customer
		if args[1] != nil {
			arg1 = args[1].(*dto.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_Orders_Call) Return(orders []dto.Order, err error) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyManageable_Orders_Call) RunAndReturn(run func(ctx context.Context, customerDTO *dto.Customer) ([]dto.Order, error)) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersAwaitingAccrual provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) OrdersAwaitingAccrual(ctx context.Context, statuses []inner.Accrual) ([]dto.Order, error) {
	ret := _mock.Called(ctx, statuses)

	if len(ret) == 0 {
		panic("no return value specified for OrdersAwaitingAccrual")
	}

	var r0 []dto.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []inner.Accrual) ([]dto.Order, error)); ok {
		return returnFunc(ctx, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []inner.Accrual) []dto.Order); ok {
		r0 = returnFunc(ctx, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []inner.Accrual) error); ok {
		r1 = returnFunc(ctx, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_OrdersAwaitingAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersAwaitingAccrual'
type MockLoyaltyManageable_OrdersAwaitingAccrual_Call struct {
	*mock.Call
}

// OrdersAwaitingAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []inner.Accrual
func (_e *MockLoyaltyManageable_Expecter) OrdersAwaitingAccrual(ctx any, statuses any) *MockLoyaltyManageable_OrdersAwaitingAccrual_Call {
	return &MockLoyaltyManageable_OrdersAwaitingAccrual_Call{Call: _e.mock.On("OrdersAwaitingAccrual", ctx, statuses)}
}

func (_c *MockLoyaltyManageable_OrdersAwaitingAccrual_Call) Run(run func(ctx context.Context, statuses []inner.Accrual)) *MockLoyaltyManageable_OrdersAwaitingAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []inner.Accrual
		if args[1] != nil {
			arg1 = args[1].([]inner.Accrual)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_OrdersAwaitingAccrual_Call) Return(orders []dto.Order, err error) *MockLoyaltyManageable_OrdersAwaitingAccrual_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyManageable_OrdersAwaitingAccrual_Call) RunAndReturn(run func(ctx context.Context, statuses []inner.Accrual) ([]dto.Order, error)) *MockLoyaltyManageable_OrdersAwaitingAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// UserLogin provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) UserLogin(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string) (string, error) {
	ret := _mock.Called(ctx, customerCredentials, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for UserLogin")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CustomerCredentials, string) (string, error)); ok {
		return returnFunc(ctx, customerCredentials, jwtSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CustomerCredentials, string) string); ok {
		r0 = returnFunc(ctx, customerCredentials, jwtSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CustomerCredentials, string) error); ok {
		r1 = returnFunc(ctx, customerCredentials, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_UserLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserLogin'
type MockLoyaltyManageable_UserLogin_Call struct {
	*mock.Call
}

// UserLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - customerCredentials dto.CustomerCredentials
//   - jwtSecret string
func (_e *MockLoyaltyManageable_Expecter) UserLogin(ctx any, customerCredentials any, jwtSecret any) *MockLoyaltyManageable_UserLogin_Call {
	return &MockLoyaltyManageable_UserLogin_Call{Call: _e.mock.On("UserLogin", ctx, customerCredentials, jwtSecret)}
}

func (_c *MockLoyaltyManageable_UserLogin_Call) Run(run func(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string)) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CustomerCredentials
		if args[1] != nil {
			arg1 = args[1].(dto.CustomerCredentials)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_UserLogin_Call) Return(s string, err error) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoyaltyManageable_UserLogin_Call) RunAndReturn(run func(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string) (string, error)) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UserRegister provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) UserRegister(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string) (string, error) {
	ret := _mock.Called(ctx, customerCredentials, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for UserRegister")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CustomerCredentials, string) (string, error)); ok {
		return returnFunc(ctx, customerCredentials, jwtSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CustomerCredentials, string) string); ok {
		r0 = returnFunc(ctx, customerCredentials, jwtSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CustomerCredentials, string) error); ok {
		r1 = returnFunc(ctx, customerCredentials, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_UserRegister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRegister'
type MockLoyaltyManageable_UserRegister_Call struct {
	*mock.Call
}

// UserRegister is a helper method to define mock.On call
//   - ctx context.Context
//   - customerCredentials dto.CustomerCredentials
//   - jwtSecret string
func (_e *MockLoyaltyManageable_Expecter) UserRegister(ctx any, customerCredentials any, jwtSecret any) *MockLoyaltyManageable_UserRegister_Call {
	return &MockLoyaltyManageable_UserRegister_Call{Call: _e.mock.On("UserRegister", ctx, customerCredentials, jwtSecret)}
}

func (_c *MockLoyaltyManageable_UserRegister_Call) Run(run func(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string)) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CustomerCredentials
		if args[1] != nil {
			arg1 = args[1].(dto.CustomerCredentials)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_UserRegister_Call) Return(s string, err error) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoyaltyManageable_UserRegister_Call) RunAndReturn(run func(ctx context.Context, customerCredentials dto.CustomerCredentials, jwtSecret string) (string, error)) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Return(run)
	return _c
}
