// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/dto"
	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoyaltyManageable creates a new instance of MockLoyaltyManageable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyManageable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyManageable {
	mock := &MockLoyaltyManageable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyManageable is an autogenerated mock type for the LoyaltyManageable type
type MockLoyaltyManageable struct {
	mock.Mock
}

type MockLoyaltyManageable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyManageable) EXPECT() *MockLoyaltyManageable_Expecter {
	return &MockLoyaltyManageable_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) Balance(ctx context.Context, userDTO *dto.User) (*model.Balance, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 *model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) (*model.Balance, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) *model.Balance); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type MockLoyaltyManageable_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyManageable_Expecter) Balance(ctx any, userDTO any) *MockLoyaltyManageable_Balance_Call {
	return &MockLoyaltyManageable_Balance_Call{Call: _e.mock.On("Balance", ctx, userDTO)}
}

func (_c *MockLoyaltyManageable_Balance_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_Balance_Call) Return(balance *model.Balance, err error) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockLoyaltyManageable_Balance_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) (*model.Balance, error)) *MockLoyaltyManageable_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdraw provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) BalanceWithdraw(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64) error {
	ret := _mock.Called(ctx, userDTO, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User, string, float64) error); ok {
		r0 = returnFunc(ctx, userDTO, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyManageable_BalanceWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdraw'
type MockLoyaltyManageable_BalanceWithdraw_Call struct {
	*mock.Call
}

// BalanceWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
//   - orderNumber string
//   - sum float64
func (_e *MockLoyaltyManageable_Expecter) BalanceWithdraw(ctx any, userDTO any, orderNumber any, sum any) *MockLoyaltyManageable_BalanceWithdraw_Call {
	return &MockLoyaltyManageable_BalanceWithdraw_Call{Call: _e.mock.On("BalanceWithdraw", ctx, userDTO, orderNumber, sum)}
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) Run(run func(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64)) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) Return(err error) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdraw_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User, orderNumber string, sum float64) error) *MockLoyaltyManageable_BalanceWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdrawals provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) BalanceWithdrawals(ctx context.Context, userDTO *dto.User) ([]model.Withdrawal, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdrawals")
	}

	var r0 []model.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) ([]model.Withdrawal, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) []model.Withdrawal); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_BalanceWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdrawals'
type MockLoyaltyManageable_BalanceWithdrawals_Call struct {
	*mock.Call
}

// BalanceWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyManageable_Expecter) BalanceWithdrawals(ctx any, userDTO any) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	return &MockLoyaltyManageable_BalanceWithdrawals_Call{Call: _e.mock.On("BalanceWithdrawals", ctx, userDTO)}
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) Return(withdrawals []model.Withdrawal, err error) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockLoyaltyManageable_BalanceWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) ([]model.Withdrawal, error)) *MockLoyaltyManageable_BalanceWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// OrderUpload provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) OrderUpload(ctx context.Context, userDTO *dto.User, number string) error {
	ret := _mock.Called(ctx, userDTO, number)

	if len(ret) == 0 {
		panic("no return value specified for OrderUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User, string) error); ok {
		r0 = returnFunc(ctx, userDTO, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyManageable_OrderUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderUpload'
type MockLoyaltyManageable_OrderUpload_Call struct {
	*mock.Call
}

// OrderUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
//   - number string
func (_e *MockLoyaltyManageable_Expecter) OrderUpload(ctx any, userDTO any, number any) *MockLoyaltyManageable_OrderUpload_Call {
	return &MockLoyaltyManageable_OrderUpload_Call{Call: _e.mock.On("OrderUpload", ctx, userDTO, number)}
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) Run(run func(ctx context.Context, userDTO *dto.User, number string)) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) Return(err error) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyManageable_OrderUpload_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User, number string) error) *MockLoyaltyManageable_OrderUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Orders provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) Orders(ctx context.Context, userDTO *dto.User) ([]model.Order, error) {
	ret := _mock.Called(ctx, userDTO)

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) ([]model.Order, error)); ok {
		return returnFunc(ctx, userDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.User) []model.Order); ok {
		r0 = returnFunc(ctx, userDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.User) error); ok {
		r1 = returnFunc(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type MockLoyaltyManageable_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
//   - ctx context.Context
//   - userDTO *dto.User
func (_e *MockLoyaltyManageable_Expecter) Orders(ctx any, userDTO any) *MockLoyaltyManageable_Orders_Call {
	return &MockLoyaltyManageable_Orders_Call{Call: _e.mock.On("Orders", ctx, userDTO)}
}

func (_c *MockLoyaltyManageable_Orders_Call) Run(run func(ctx context.Context, userDTO *dto.User)) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.User
		if args[1] != nil {
			arg1 = args[1].(*dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_Orders_Call) Return(orders []model.Order, err error) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyManageable_Orders_Call) RunAndReturn(run func(ctx context.Context, userDTO *dto.User) ([]model.Order, error)) *MockLoyaltyManageable_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// UserLogin provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) UserLogin(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string) (string, error) {
	ret := _mock.Called(ctx, userCredentials, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for UserLogin")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserCredentials, string) (string, error)); ok {
		return returnFunc(ctx, userCredentials, jwtSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserCredentials, string) string); ok {
		r0 = returnFunc(ctx, userCredentials, jwtSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UserCredentials, string) error); ok {
		r1 = returnFunc(ctx, userCredentials, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_UserLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserLogin'
type MockLoyaltyManageable_UserLogin_Call struct {
	*mock.Call
}

// UserLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - userCredentials dto.UserCredentials
//   - jwtSecret string
func (_e *MockLoyaltyManageable_Expecter) UserLogin(ctx any, userCredentials any, jwtSecret any) *MockLoyaltyManageable_UserLogin_Call {
	return &MockLoyaltyManageable_UserLogin_Call{Call: _e.mock.On("UserLogin", ctx, userCredentials, jwtSecret)}
}

func (_c *MockLoyaltyManageable_UserLogin_Call) Run(run func(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string)) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UserCredentials
		if args[1] != nil {
			arg1 = args[1].(dto.UserCredentials)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_UserLogin_Call) Return(s string, err error) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoyaltyManageable_UserLogin_Call) RunAndReturn(run func(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string) (string, error)) *MockLoyaltyManageable_UserLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UserRegister provides a mock function for the type MockLoyaltyManageable
func (_mock *MockLoyaltyManageable) UserRegister(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string) (string, error) {
	ret := _mock.Called(ctx, userCredentials, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for UserRegister")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserCredentials, string) (string, error)); ok {
		return returnFunc(ctx, userCredentials, jwtSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserCredentials, string) string); ok {
		r0 = returnFunc(ctx, userCredentials, jwtSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UserCredentials, string) error); ok {
		r1 = returnFunc(ctx, userCredentials, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyManageable_UserRegister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRegister'
type MockLoyaltyManageable_UserRegister_Call struct {
	*mock.Call
}

// UserRegister is a helper method to define mock.On call
//   - ctx context.Context
//   - userCredentials dto.UserCredentials
//   - jwtSecret string
func (_e *MockLoyaltyManageable_Expecter) UserRegister(ctx any, userCredentials any, jwtSecret any) *MockLoyaltyManageable_UserRegister_Call {
	return &MockLoyaltyManageable_UserRegister_Call{Call: _e.mock.On("UserRegister", ctx, userCredentials, jwtSecret)}
}

func (_c *MockLoyaltyManageable_UserRegister_Call) Run(run func(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string)) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UserCredentials
		if args[1] != nil {
			arg1 = args[1].(dto.UserCredentials)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoyaltyManageable_UserRegister_Call) Return(s string, err error) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoyaltyManageable_UserRegister_Call) RunAndReturn(run func(ctx context.Context, userCredentials dto.UserCredentials, jwtSecret string) (string, error)) *MockLoyaltyManageable_UserRegister_Call {
	_c.Call.Return(run)
	return _c
}
