// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package loyalty

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/model"
	"github.com/RAdevelop/ya_practicum-go-advanced-ext-diplom/internal/status/inner"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoyaltyStorage creates a new instance of MockLoyaltyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyStorage {
	mock := &MockLoyaltyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyStorage is an autogenerated mock type for the LoyaltyStorage type
type MockLoyaltyStorage struct {
	mock.Mock
}

type MockLoyaltyStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyStorage) EXPECT() *MockLoyaltyStorage_Expecter {
	return &MockLoyaltyStorage_Expecter{mock: &_m.Mock}
}

// BalanceAccrual provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceAccrual(ctx context.Context, accrual model.Accrual) error {
	ret := _mock.Called(ctx, accrual)

	if len(ret) == 0 {
		panic("no return value specified for BalanceAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Accrual) error); ok {
		r0 = returnFunc(ctx, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyStorage_BalanceAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceAccrual'
type MockLoyaltyStorage_BalanceAccrual_Call struct {
	*mock.Call
}

// BalanceAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - accrual model.Accrual
func (_e *MockLoyaltyStorage_Expecter) BalanceAccrual(ctx any, accrual any) *MockLoyaltyStorage_BalanceAccrual_Call {
	return &MockLoyaltyStorage_BalanceAccrual_Call{Call: _e.mock.On("BalanceAccrual", ctx, accrual)}
}

func (_c *MockLoyaltyStorage_BalanceAccrual_Call) Run(run func(ctx context.Context, accrual model.Accrual)) *MockLoyaltyStorage_BalanceAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Accrual
		if args[1] != nil {
			arg1 = args[1].(model.Accrual)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceAccrual_Call) Return(err error) *MockLoyaltyStorage_BalanceAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceAccrual_Call) RunAndReturn(run func(ctx context.Context, accrual model.Accrual) error) *MockLoyaltyStorage_BalanceAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceByCustomerID provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceByCustomerID(ctx context.Context, customerID uint64) (*model.Balance, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for BalanceByCustomerID")
	}

	var r0 *model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*model.Balance, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *model.Balance); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_BalanceByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceByCustomerID'
type MockLoyaltyStorage_BalanceByCustomerID_Call struct {
	*mock.Call
}

// BalanceByCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uint64
func (_e *MockLoyaltyStorage_Expecter) BalanceByCustomerID(ctx any, customerID any) *MockLoyaltyStorage_BalanceByCustomerID_Call {
	return &MockLoyaltyStorage_BalanceByCustomerID_Call{Call: _e.mock.On("BalanceByCustomerID", ctx, customerID)}
}

func (_c *MockLoyaltyStorage_BalanceByCustomerID_Call) Run(run func(ctx context.Context, customerID uint64)) *MockLoyaltyStorage_BalanceByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceByCustomerID_Call) Return(balance *model.Balance, err error) *MockLoyaltyStorage_BalanceByCustomerID_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceByCustomerID_Call) RunAndReturn(run func(ctx context.Context, customerID uint64) (*model.Balance, error)) *MockLoyaltyStorage_BalanceByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdraw provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceWithdraw(ctx context.Context, withdrawal model.Withdrawal) error {
	ret := _mock.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Withdrawal) error); ok {
		r0 = returnFunc(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyStorage_BalanceWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdraw'
type MockLoyaltyStorage_BalanceWithdraw_Call struct {
	*mock.Call
}

// BalanceWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal model.Withdrawal
func (_e *MockLoyaltyStorage_Expecter) BalanceWithdraw(ctx any, withdrawal any) *MockLoyaltyStorage_BalanceWithdraw_Call {
	return &MockLoyaltyStorage_BalanceWithdraw_Call{Call: _e.mock.On("BalanceWithdraw", ctx, withdrawal)}
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) Run(run func(ctx context.Context, withdrawal model.Withdrawal)) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Withdrawal
		if args[1] != nil {
			arg1 = args[1].(model.Withdrawal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) Return(err error) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdraw_Call) RunAndReturn(run func(ctx context.Context, withdrawal model.Withdrawal) error) *MockLoyaltyStorage_BalanceWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceWithdrawalsByCustomerID provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) BalanceWithdrawalsByCustomerID(ctx context.Context, customerID uint64) ([]model.Withdrawal, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdrawalsByCustomerID")
	}

	var r0 []model.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]model.Withdrawal, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []model.Withdrawal); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdrawalsByCustomerID'
type MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call struct {
	*mock.Call
}

// BalanceWithdrawalsByCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uint64
func (_e *MockLoyaltyStorage_Expecter) BalanceWithdrawalsByCustomerID(ctx any, customerID any) *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call {
	return &MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call{Call: _e.mock.On("BalanceWithdrawalsByCustomerID", ctx, customerID)}
}

func (_c *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call) Run(run func(ctx context.Context, customerID uint64)) *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call) Return(withdrawals []model.Withdrawal, err error) *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call) RunAndReturn(run func(ctx context.Context, customerID uint64) ([]model.Withdrawal, error)) *MockLoyaltyStorage_BalanceWithdrawalsByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// CustomerCreate provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) CustomerCreate(ctx context.Context, customer *model.Customer) (*model.Customer, error) {
	ret := _mock.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for CustomerCreate")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) (*model.Customer, error)); ok {
		return returnFunc(ctx, customer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) *model.Customer); ok {
		r0 = returnFunc(ctx, customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Customer) error); ok {
		r1 = returnFunc(ctx, customer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_CustomerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomerCreate'
type MockLoyaltyStorage_CustomerCreate_Call struct {
	*mock.Call
}

// CustomerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *model.Customer
func (_e *MockLoyaltyStorage_Expecter) CustomerCreate(ctx any, customer any) *MockLoyaltyStorage_CustomerCreate_Call {
	return &MockLoyaltyStorage_CustomerCreate_Call{Call: _e.mock.On("CustomerCreate", ctx, customer)}
}

func (_c *MockLoyaltyStorage_CustomerCreate_Call) Run(run func(ctx context.Context, customer *model.Customer)) *MockLoyaltyStorage_CustomerCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_CustomerCreate_Call) Return(customer1 *model.Customer, err error) *MockLoyaltyStorage_CustomerCreate_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *MockLoyaltyStorage_CustomerCreate_Call) RunAndReturn(run func(ctx context.Context, customer *model.Customer) (*model.Customer, error)) *MockLoyaltyStorage_CustomerCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CustomerFindByLogin provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) CustomerFindByLogin(ctx context.Context, login string) (*model.Customer, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for CustomerFindByLogin")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_CustomerFindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomerFindByLogin'
type MockLoyaltyStorage_CustomerFindByLogin_Call struct {
	*mock.Call
}

// CustomerFindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockLoyaltyStorage_Expecter) CustomerFindByLogin(ctx any, login any) *MockLoyaltyStorage_CustomerFindByLogin_Call {
	return &MockLoyaltyStorage_CustomerFindByLogin_Call{Call: _e.mock.On("CustomerFindByLogin", ctx, login)}
}

func (_c *MockLoyaltyStorage_CustomerFindByLogin_Call) Run(run func(ctx context.Context, login string)) *MockLoyaltyStorage_CustomerFindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_CustomerFindByLogin_Call) Return(customer *model.Customer, err error) *MockLoyaltyStorage_CustomerFindByLogin_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockLoyaltyStorage_CustomerFindByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (*model.Customer, error)) *MockLoyaltyStorage_CustomerFindByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// OrderUpload provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) OrderUpload(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for OrderUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyStorage_OrderUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderUpload'
type MockLoyaltyStorage_OrderUpload_Call struct {
	*mock.Call
}

// OrderUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockLoyaltyStorage_Expecter) OrderUpload(ctx any, order any) *MockLoyaltyStorage_OrderUpload_Call {
	return &MockLoyaltyStorage_OrderUpload_Call{Call: _e.mock.On("OrderUpload", ctx, order)}
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) Run(run func(ctx context.Context, order model.Order)) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) Return(err error) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyStorage_OrderUpload_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *MockLoyaltyStorage_OrderUpload_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersAwaitingAccrual provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) OrdersAwaitingAccrual(accruals []inner.Accrual) ([]model.Order, error) {
	ret := _mock.Called(accruals)

	if len(ret) == 0 {
		panic("no return value specified for OrdersAwaitingAccrual")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]inner.Accrual) ([]model.Order, error)); ok {
		return returnFunc(accruals)
	}
	if returnFunc, ok := ret.Get(0).(func([]inner.Accrual) []model.Order); ok {
		r0 = returnFunc(accruals)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]inner.Accrual) error); ok {
		r1 = returnFunc(accruals)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_OrdersAwaitingAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersAwaitingAccrual'
type MockLoyaltyStorage_OrdersAwaitingAccrual_Call struct {
	*mock.Call
}

// OrdersAwaitingAccrual is a helper method to define mock.On call
//   - accruals []inner.Accrual
func (_e *MockLoyaltyStorage_Expecter) OrdersAwaitingAccrual(accruals any) *MockLoyaltyStorage_OrdersAwaitingAccrual_Call {
	return &MockLoyaltyStorage_OrdersAwaitingAccrual_Call{Call: _e.mock.On("OrdersAwaitingAccrual", accruals)}
}

func (_c *MockLoyaltyStorage_OrdersAwaitingAccrual_Call) Run(run func(accruals []inner.Accrual)) *MockLoyaltyStorage_OrdersAwaitingAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []inner.Accrual
		if args[0] != nil {
			arg0 = args[0].([]inner.Accrual)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_OrdersAwaitingAccrual_Call) Return(orders []model.Order, err error) *MockLoyaltyStorage_OrdersAwaitingAccrual_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyStorage_OrdersAwaitingAccrual_Call) RunAndReturn(run func(accruals []inner.Accrual) ([]model.Order, error)) *MockLoyaltyStorage_OrdersAwaitingAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersByCustomerID provides a mock function for the type MockLoyaltyStorage
func (_mock *MockLoyaltyStorage) OrdersByCustomerID(ctx context.Context, customerID uint64) ([]model.Order, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for OrdersByCustomerID")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]model.Order, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []model.Order); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoyaltyStorage_OrdersByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersByCustomerID'
type MockLoyaltyStorage_OrdersByCustomerID_Call struct {
	*mock.Call
}

// OrdersByCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uint64
func (_e *MockLoyaltyStorage_Expecter) OrdersByCustomerID(ctx any, customerID any) *MockLoyaltyStorage_OrdersByCustomerID_Call {
	return &MockLoyaltyStorage_OrdersByCustomerID_Call{Call: _e.mock.On("OrdersByCustomerID", ctx, customerID)}
}

func (_c *MockLoyaltyStorage_OrdersByCustomerID_Call) Run(run func(ctx context.Context, customerID uint64)) *MockLoyaltyStorage_OrdersByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoyaltyStorage_OrdersByCustomerID_Call) Return(orders []model.Order, err error) *MockLoyaltyStorage_OrdersByCustomerID_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLoyaltyStorage_OrdersByCustomerID_Call) RunAndReturn(run func(ctx context.Context, customerID uint64) ([]model.Order, error)) *MockLoyaltyStorage_OrdersByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}
